permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Surf 1685"
  description: Surf 1685's vision is to be known as the top of the market for all surf gear. The website allows surfers of every experience level to purchase items such as wetsuits, swimwear, and cover-ups, while ensuring quality and top-of-the-line trends.
  font_url: "https://use.typekit.net/iyq3xwy.css"
  colors:
    background: "--color-primary-light"
    accent: "--color-accent"
  rationales:
      typefaces.primary: |
        Brandon Grotesque was selected because it's a geometric, smooth font that is designed for readability. The geometric elements contrast the smoothness of waves, while creating a modern look and feel for the website.
      colors.primary: |
        The primary colours represent the sand on beaches and sand dunes. The primary colour should be used for headers, footers, buttons, and the primary light colour should be used for the background.
      colors.secondary: |
        The secondary colour continues with the natural, sea-themed tones. It is a deep blue-the colour of the bottom of the sea. It should be used for and text.
      color.accent: |
        The accent colours are vibrant, slightly exaggerated colours of natural elements, such as a sunrise and seaweed. Each of the names are meant to remind the viewer of that element.
      basic-button: |
        The basic button should be used in almost all situations.
      button-light: |
        The light button should be used exculsively in the footer. It is used to refer the site to a friend, or to provide feedback about the site.
