permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Surf 1685"
  description: Surf 1685's vision is to be known as the top of the market for all surf gear. The website allows surfers of every experience level to purchase items such as wetsuits, swimwear, and cover-ups, while ensuring quality and top-of-the-line trends.
  font_url: "https://use.typekit.net/iyq3xwy.css"
  colors:
    background: "--color-primary-light: #fffdf6;"
    accent: "--color-accent: #ee6352;"
    patterns:
      brand.logos: "--color-primary-light: #fffdf6;"
  rationales:
      typefaces.primary: |
        Brandon Grotesque was selected because it's a geometric, smooth font that is designed for readability. The geometric elements contrast the smoothness of waves, while creating a modern look and feel for the website.
