title: "Footer"
description: |
  The footer is to be placed at the bottom of every page of the website.

patterns:
  footer:
    fields:
      - name: button_left
        type: string
        example: "Refer a friend for an extra 20% off!"
      - name: button_right
        type: string
        example: "Do you have any feedback for us?"
