title: "Footer"
description: |
  The footer is to be placed at the bottom of every page of the website.

patterns:
  footer:
    fields:
      - name: text
        type: string
        example: "Want an extra 20% off? Refer a friend."
      - name: button_text
        type: string
        example: "Do you have any feedback for us?"
