title: "Buttons"
description: |
  Buttons should be used in different situation where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen. It is okay to change the 'font-size' class of the buttons to make them different sizes.

patterns:
  basic:
    width: "12em"
    fields:
      - name: button_text
        type: string
        example: "Shop Now"
      - name: url
        type: url
        example: "/women/"
    description: |
      The basic button should be used in almost all situations.
  basic-long:
    fields:
      - name: button_text
        type: string
        example: "Shop Now"
      - name: url
        type: url
        example: "/"
    description: |
      The basic long button is used to create extended buttons. It is only to be used when absolutely necessary. An example of this situation would be when the button is required to fill a space in order to balance a grid.
  light:
    fields:
      - name: button_text
        type: string
        example: "WANT AN EXTRA 20% OFF? Refer a friend."
      - name: url
        type: url
        example: "/"
    description: |
      The light button should be used exculsively in the footer. It is used to refer the site to a friend, or to provide feedback about the site.
  favourite-button:
    description: |
      The favourite button is used to add an item to the user's collection of favourite products on the site.
