title: "Buttons"
description: |
  Buttons should be used in different situation where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    width: "12em"
    description: |
      The basic button should be used in almost all situations.
  basic-long:
    description: |
      The basic long button is used to create extended buttons.
  light:
    description: |
      The light button should be used exculsively in the footer. It is used to refer the site to a friend, or to provide feedback about the site.
    fields:
      - name: text
        type: string
        example: "WANT AN EXTRA 20% OFF? Refer a friend."
  favourite-button:
    description: |
      The favourite button is used to add an item to the user's collection of favourite products on the site.
