title: "Header"
description: |
  The header is placed at the top of each page. It includes the logo and the navigation that the users are most interested in.

patterns:
  header:
    fields:
      - name: url
        type: url
        example: "/womens-swim/"
    description: |
      The basic button should be used in almost all situations.
