title: "Forms"
description: |
  Forms are used to fill out information in order to purchase products from Surf 1685. They are also used to subscribe to recieving promotional emails.

patterns:

  checkbox:
    fields:
      - name: details
        type: string
        example: "I Agree"
    description: |
      The checkbox is used to select one or more items.

  email-signup:
    title: Email
    fields:
      - name: title
        type: string
        example: "Email Address (Where we will send your receipt and tracking info)"
    description: |
      This input field is to be used for emails only.

  fieldset:
    description: |
      The fieldset is used to clearly identify one section in a form from another.
    fields:
      - name: title
        type: string
        example: "Contact Info"

  select:
    width: 400
    description: |
      The user can select one option from a list.
    fields:
    - name: title
      type: string
      example: "Province"
      - name: title
        type: string
        example: "Select a Province"
      - name: option-1
        type: string
        example: "Alberta"
      - name: option-2
        type: string
        example: "British Columbia"
      - name: option-3
        type: string
        example: "Manitoba"
      - name: option-4
        type: string
        example: "New Brunswick"
      - name: option-5
        type: string
        example: "Newfoundland & Labrador"
      - name: option-6
        type: string
        example: "Northwest Territories"
      - name: option-7
        type: string
        example: "Nova Scotia"
      - name: option-8
        type: string
        example: "Nunavut"
      - name: option-9
        type: string
        example: "Ontario"
      - name: option-10
        type: string
        example: "Prince Edward Island"
      - name: option-11
        type: string
        example: "Québec"
      - name: option-12
        type: string
        example: "Saskatchewan"
      - name: option-13
        type: string
        example: "Yukon"
      - name: error-message
        type: string
        example: "Please select a Province"

  information-container:
    description: |
      The information container is used to inform the user about the shipping costs. The use of the different background colour allows for them to be able to easily scan the page to find out how much it will cost.
    fields:
      - name: arrival
        type: string
        example: "Arrives by February 04"
      - name: arrival
        type: string
        example: "$9.25 CAD Shipping"

  basic-input:
    fields:
      - name: title
        type: string
        example: "Name"
    description: |
      The basic input is the most commonly used input and should be used in most situations.

  form-error-message:
    description: |
      Error messages are visually displayed close to the field which has an error, and are accessible.
