title: "Forms"
description: |
  Forms are used to fill out information in order to purchase products from Surf 1685. They are also used to subscribe to recieving promotional emails.

patterns:
  checkbox:
    fields:
      - name: details
        type: string
        example: "I Agree"
    description: |
      The checkbox is used to select from a set of one or more choices.
  email-signup:
    fields:
      - name: title
        type: string
        example: "Email Address (Where we will send your receipt and tracking info)"
      - name: details
        type: string
        example: "Sign me up"
    description: |
      The checkbox is used to select from a set of one or more choices.
  fieldset:
    description: |
      The fieldset is used to clearly identify one section in a form from another.
  form-dropdown:
    width: 400
  information-container:
    description: |
      The information container is used to inform the user about the shipping costs. The use of the different background colour allows for them to be able to easily scan the page to find out how much it will cost.
  text-input:
    width: 450
    fields:
      - name: title
        type: string
        example: "Name"
