title: "Forms"
description: |
  Forms are used to fill out information in order to purchase products from Surf 1685. They are also used to subscribe to recieving promotional emails.

patterns:
  form-dropdown:
    width: 400
  form:
    width: 450
