title: "Forms"
description: |
  Forms are used to fill out information in order to purchase products from Surf 1685. They are also used to subscribe to recieving promotional emails.

patterns:
  checkbox:
    title: "Checkbox"
    fields:
      - name: details
        type: string
        example: "I Agree"
    description: |
      The checkbox is used to select one or more items.

  email-signup:
    title: Email Signup
    fields:
      - name: title
        type: string
        example: "Email Address (Where we will send your receipt and tracking info)"
    description: |
      This input field is to be used for emails only.

  fieldset:
    title: "Fieldset"
    description: |
      The fieldset is used to clearly identify one section in a form from another.
    fields:
      - name: title
        type: string
        example: "Contact Info"

  select:
    title: "Dropdown"
    description: |
      The user can select one option from a list.
    fields:
      - name: title-1
        type: string
        example: "Province"
      - name: placeholder-1
        type: string
        example: "Select a Province"
      - name: option_1
        type: string
        example: "Alberta"
      - name: option_2
        type: string
        example: "British Columbia"
      - name: option_3
        type: string
        example: "Manitoba"
      - name: option_4
        type: string
        example: "New Brunswick"
      - name: option_5
        type: string
        example: "Newfoundland & Labrador"
      - name: option_6
        type: string
        example: "Northwest Territories"
      - name: option_7
        type: string
        example: "Nova Scotia"
      - name: option_8
        type: string
        example: "Nunavut"
      - name: option_9
        type: string
        example: "Ontario"
      - name: option_10
        type: string
        example: "Prince Edward Island"
      - name: option_11
        type: string
        example: "Québec"
      - name: option_12
        type: string
        example: "Saskatchewan"
      - name: option_13
        type: string
        example: "Yukon"
      - name: error-message
        type: string
        example: "Please select a Province"

  information-container:
    title: "Information Container"
    description: |
      The information container is used to inform the user about the shipping costs. The use of the different background colour allows for them to be able to easily scan the page to find out how much it will cost.
    fields:
      - name: arrival
        type: string
        example: "Arrives by February 04"
      - name: arrival
        type: string
        example: "$9.25 CAD Shipping"

  basic-input:
    title: "Basic Input"
    fields:
      - name: title
        type: string
        example: "Name"
    description: |
      The basic input is the most commonly used input and should be used in most situations.

  form-error-message:
    title: "Form Error Message"
    description: |
      Error messages are visually displayed close to the field which has an error, and are accessible.
