patterns:
  image-card:
    width 400
    fields:
      - name: title
        type: string
        example: "Surf 1685 Surf Bikini Top"
      - name: details
        type: string
        example: ""$65.00 CAD"
      - name: images
        type: images
        example: "surf1685-surf-bikini-top.jpg"
      - name: button_text
        type: string
        example: "Shop Now"
