title: "Buttons"
description: |
  Cards are used to display content composed of different types of objects that are related. They are also well-suited for presenting photos and products with captions of variable lengths.

patterns:
  product-card:
    width 400
    fields:
      - name: title
        type: string
        example: "Surf 1685 Surf Bikini Top"
      - name: details
        type: string
        example: ""$65.00 CAD"
      - name: images
        type: images
        example: "surf1685-surf-bikini-top.jpg"
      - name: button_text
        type: string
        example : "Shop Now"
    description: |
      The product card is the standard card for featuring products in the shop. The content is arrange in the order of: image, then the price below (if applicaple), and below that, the name of the product.
