title: "Cards"
description: |
  Cards are used to display content composed of different types of objects that are related. They are also well-suited for presenting photos and products with captions of variable lengths.

patterns:
  product-card:
    description: |
      The product card is the standard card for featuring products in the shop. The content is arrange in the order of: image, the name of the product, the price below, and a button that links to the product details page.
    fields:
      - name: data
        object: object
        data:
          source: "site.womens-swim[0]"
          type: _womens-swim

  image-card:
    width: 400
    description: |
      The image card is used for featuring images that people have posted on social media. They have either tagged #Surf1685, or tagged @Surf1685, or have done both. It is always in a square format, is displayed on the home page only, and there are three of the images shown at a time.
    fields:
      - name: image
        type: images
        example: "palm-tree-rows.jpg"

  product-card-category:
    description: |
      The product card is the card used to show each product category. The content is arrange in the order of: image representing category, the name of the category, and a button that links to the category collection.
    fields:
      - name: data
        object: object
        data:
          source: "site.products[0]"
          type: Category
      - name: title
        type: string
        example: "Shop Women's Bathing Suits"
      - name: image
        type: images
        example: "classic-surf-bikini-top.jpg"
      - name: button_text
        type: string
        example: "View Collection"

  recently-viewed:
    title: "Recently Viewed"
    description: |
      The "recently viewed" card is used exclusively on the product details page. It features the products that the user has most recently viewed on the site and is located beneath the Ratings & Reviews section.
    fields:
      - name: title
        type: string
        example: "High Heights One-Piece Swim"
      - name: image
        type: images
        example: "/products/high-heights-one-piece-swim.jpg"
