title: "Navigation"
description: |
  The navigations are used to guide the user through the website.

patterns:
  secondary-nav:
    title: Secondary Navigation
    width:
    description: |
      This secondary nav is located in the sidebar. It is content that is of secondary interest to the user.
  details:
      title: Details
      description: The details section gives more information about the product.
