title: "Navigation"
description: |
  The navigation and sections are used to guide the user through the website.

patterns:
  secondary-nav:
    title: Secondary Navigation
    description: |
      This secondary nav is located in the sidebar. It is content that is of secondary interest to the user.
  social-icon-nav:
    title: "Social Icon Navigation"
    description: |
      The Social icon nav is located in the footer. It connects the user to Surf 1685's main social networks.
  introduction:
    title: "Sample Paragraph"
    description: |
      Some introductory text for the website. To be used for long chunks of important text. An example of this would be on the home page, for an "About" section.
    fields:
      - name: intro-text
        type: string
        example: "Some introductory text for the website. To be used for long chunks of important text. Some introductory text for the website."
