title: "Navigation"
description: |
  The navigation and sections are used to guide the user through the website.

patterns:
  secondary-nav:
    title: Secondary Navigation
    width:
    description: |
      This secondary nav is located in the sidebar. It is content that is of secondary interest to the user.
  product:
    title: "Product"
    fields:
      - name: text-1
        type: string
        example: "Add to Bag"
      - name: text-2
        type: string
        example: "Find in Store"
    description: |
      The details section gives more information on the product cost, colours, and sizes available.
  social-icon-nav:
    title: "Social Icon Navigation"
    description: |
      The Social icon nav is located in the footer. It connects the user to Surf 1685's main social networks.
  icon-navigation:
    title: "Icon Navigation"
    description: |
      The icon navigation is located in the header. It connects the user the search bar, their favourite items, and their shopping bag.
  item-details:
    title: "Item Details"
    description: |
      The item details contain information on the product specifics.
  size:
    title: "Size"
    description: |
      A dropdown that allows the user to choose the size of the product that they wish to purchase.
