title: "Product Information"
description: |
  The product information gives the user key details about the product that they are looking at.

patterns:
  product-colour:
    title: Product Colour
    description: |
      The product colour shows which colours the product is available in. It is located on the product details page.
    fields:
      - name: image
        type: images
        example: "white.jpg"
      - name: colour
        type: string
        example: "White"

  item-details:
    title: "Item Details"
    description: |
      The item details contains information on the product specifics. It is located on the product details page.
    fields:
      - name: details-1
        type: string
        example: "Comfy nylon with the right amount of stretch"
      - name: details-2
        type: string
        example: "Style: 4577-4568"
      - name: details-3
        type: string
        example: ""
      - name: materials-1
        type: string
        example: "100% Polyester"
      - name: materials-2
        type: string
        example: "Use a mild detergent and cool water"
      - name: materials-3
        type: string
        example: "Imported"
      - name: size-and-fit-1
        type: string
        example: "Super scoop neckline"
      - name: size-and-fit-2
        type: string
        example: "Removable soft padding"
      - name: size-and-fit-3
        type: string
        example: "True to size"

  product:
    title: "Product Information"
    description: |
      The product information section gives more information on the product cost, colours, and sizes available. The user can find this on the product details page.
    fields:
      - name: text-1
        type: string
        example: "Add to Bag"
      - name: text-2
        type: string
        example: "Find in Store"
      - name: image
        type: images
        example: "white.jpg"
      - name: colour
        type: images
        example: "white.jpg"

  size:
    title: "Size"
    description: |
      This dropdown that allows the user to choose the size of the product that they wish to purchase. It all of the content can be replaced so that it can also be used as a filter, or another necessary dropdown. It is located on the product details page, and on the products page.
    fields:
      - name: title
        type: string
        example: "Size"
      - name: placeholder
        type: string
        example: "Select a Size"
      - name: option-1
        type: string
        example: "XS"
      - name: option-2
        type: string
        example: "S"
      - name: option-3
        type: string
        example: "M"
      - name: option-4
        type: string
        example: "L"
      - name: option-5
        type: string
        example: "XL"
      - name: error-message
        type: string
        example: "Please select a Size"

  product-details-image:
    title: Product Details image
    description: |
      This collection of images shows the product at different angles so that the user can get a good idea of what the product looks like before they consider buying it.
    fields:
      - name: image-large
        type: images
        example: "products/callie-one-piece.jpg"
      - name: image-small-1
        type: images
        example: "products/callie-one-piece.jpg"
      - name: image-small-2
        type: images
        example: "products/callie-one-piece.jpg"
