title: "Product Information"
description: |
  The product information gives the user key details about the product that they are looking at.

patterns:
  product-colour:
    title: Product Colour
    description: |
      The product colour shows which colours the product is available in.
    fields:
      - name: image
        type: images
        example: "white.jpg"
      - name: colour
        type: string
        example: "White"
  item-details:
    title: "Item Details"
    description: |
      The item details contain information on the product specifics.
    fields:
      - name: details-1
        type: string
        example: "Side cut outs"
      - name: details-2
        type: string
        example: "Anyone will look great in this!"
      - name: details-3
        type: string
        example: "Style: 5609-1034"
      - name: materials-1
        type: string
        example: "100% Polyester"
      - name: materials-2
        type: string
        example: "Use a mild detergent and cool water"
      - name: materials-3
        type: string
        example: "Imported"
      - name: size-and-fit-1
        type: string
        example: "Lightly padded"
      - name: size-and-fit-2
        type: string
        example: "Fully lined"
      - name: size-and-fit-3
        type: string
        example: "True to size"

  product:
    title: "Product"
    description: |
      The details section gives more information on the product cost, colours, and sizes available.
    fields:
      - name: text-1
        type: string
        example: "Add to Bag"
      - name: text-2
        type: string
        example: "Find in Store"
      - name: image
        type: images
        example: "white.jpg"
      - name: colour
        type: images
        example: "white.jpg"

  size:
    title: "Size"
    description: |
      A dropdown that allows the user to choose the size of the product that they wish to purchase.
    fields:
      - name: title
        type: string
        example: "Size"
      - name: placeholder
        type: string
        example: "Select a Size"
      - name: option-1
        type: string
        example: "XS"
      - name: option-2
        type: string
        example: "S"
      - name: option-3
        type: string
        example: "M"
      - name: option-4
        type: string
        example: "L"
      - name: option-5
        type: string
        example: "XL"
      - name: error-message
        type: string
        example: "Please select a Size"
